CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "notes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "title" varchar,
  "content" text,
  "pinned" boolean DEFAULT false,
  "archived" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "note_tags" (
  "note_id" int NOT NULL,
  "tag_id" int NOT NULL,
  PRIMARY KEY ("note_id", "tag_id")
);

COMMENT ON TABLE "users" IS 'Registered users for login/registration';

COMMENT ON TABLE "notes" IS 'All notes — can belong to a user or be anonymous (free mode)';

COMMENT ON TABLE "tags" IS 'Tags to organize notes — private to each user';

COMMENT ON TABLE "note_tags" IS 'Many-to-many mapping between notes and tags';

ALTER TABLE "notes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "tags" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "note_tags" ADD FOREIGN KEY ("note_id") REFERENCES "notes" ("id");

ALTER TABLE "note_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id");
